theme: jekyll-theme-cayman

# Welcome to Andrew's Fun Website (kinda)

# Socials: 

I dont really have any so you can have my discord Andre-w#4885

# Things about me
- I touched grass last month (trust)
- I eat a lot
- I like playing games

# Hobbies
- playing games
- hanging out with friends
- Going outside
